### ISSUE TITLE
碰到了个问题，执行命令后报错

### ISSUE THREAD

**Issue by v2-share** [ershiyi21/myprogram#1]
root@:~# sudo apt-get install make git zlib1g-dev libssl-dev gperf cmake clang-10 libc++-dev libc++abi-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package clang-10 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'clang-10' has no installation candidate

**Comment by v2-share** [comment]
继续执行，碰到第二个问题
root@:~/telegram-bot-api/build# CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
CMake Error at /usr/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:

  /usr/bin/clang++-10.

Call Stack (most recent call first):
  CMakeLists.txt:9 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/root/telegram-bot-api/build/CMakeFiles/CMakeOutput.log".
root@:~/telegram-bot-api/build# cmake --build . --target install
gmake: *** No rule to make target 'install'.  Stop.

**Comment by ershiyi21** [comment]
1. 关于搭建自己的telegram-bot-api，借助的是[github项目](https://github.com/tdlib/telegram-bot-api)，具体步骤[此处有介绍](https://tdlib.github.io/telegram-bot-api/build.html)，选择自己的系统，按步骤编译就行，若为国内服务器，请确保网络正常，编译比较耗时；
2. 个人建议，若非arm处理器，和博客中介绍的一样，使用docker一步即可搭建完成

**Comment by v2-share** [comment]
感谢分享，已经完美运行了，但是反馈个小BUG，不过不知道是不是您特意这样设置的
问题复现：当多张图片被转发给机器人时，不管有没有文字在转发的消息中，机器人都会转存图片到miedia_group中新建一个文件夹，然后把图片存到其中，而不是把图片根据分类转存到photos中，这样比较不利于管理，能否教一下怎么解决这个问题？十分感谢！

**Comment by ershiyi21** [comment]
针对多文件的信息，比如多张图片，或者多个视频，或者混合内容的，都是单独放置在media_group目录下，为什么不进行分类呢？因为大部分多文件信息既包含图片，又包含视频或者其他，这时只有它们全部在一起，才能表示出该条信息的意义，比如影片信息，可能“海报+预告片”，二者都在，程序不好归类，若将海报单独分到图片，预告片分到视频，无意义

对于你反馈的多张图片的消息，全部放置到photo目录下，程序上比较麻烦。对于多文件信息，如果想按文件类型分类，不放置到media_group下，一个文件一个文件的多次转发就好

**Comment by v2-share** [comment]
感谢~  大佬，今晚弄了一晚上，出个了bug,{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}   自建接口经常报错409，说有另一个机器人在运行，您碰到过吗

**Comment by ershiyi21** [comment]
> 感谢~ 大佬，今晚弄了一晚上，出个了bug,{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"} 自建接口经常报错409，说有另一个机器人在运行，您碰到过吗

不清楚，我自己使用不存在这个问题，一个机器人只干一件事情，该机器人不要用于其它程序
